sudo: required
language: python
install:
  - wget https://github.com/jgm/pandoc/releases/download/1.17/pandoc-1.17-1-amd64.deb && sudo dpkg -i pandoc-1.17-1-amd64.deb
  - pip install pyyaml GitPython pypandoc
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to run tests
script: python setup.py test
